/**
 * Takes the web's per-instrument variations of a style — Merengue's "Var 1" to "Var 8" and
 * "All together" on the bass, and the rest — to the app, which had only the first of each.
 *
 *   npm run variations:export
 *
 * They are written as the steps the shared engine plays (degreeSlots, the same packing the
 * web sends it), so a variation sounds in the app exactly as it does here. Only styles with
 * more than one variation on a track, and only the ones the app has too.
 *
 * Output: lib/core/data/style_variations.g.dart in the app repo (read by StylePreset.variations).
 * Env: CHORD_APP  the app repo (default C:/Users/Eliascorsino/Projects/chord_sequencer)
 */
import fs from 'node:fs';
import path from 'node:path';
import { MUSICAL_STYLES, getSlotsPerBar } from '../src/lib/styles';
import { degreeSlots } from '../src/lib/appEngine/fromSong';
import { type BassScaleData } from '../src/lib/bassScale';

const app = process.env.CHORD_APP || 'C:/Users/Eliascorsino/Projects/chord_sequencer';
/** The web's style id → the app's (lib/core/data/style_presets.dart). */
const APP_ID: Record<string, string> = { merengue: 'merengue', coritos: 'coritos', funk: 'funk', reggaeton: 'reggaeton', soul_rnb: 'rnb', jazz_light: 'jazz' };
const TRACKS = ['bass', 'piano', 'guitar'] as const;

const out: string[] = [];
let count = 0;
for (const style of MUSICAL_STYLES) {
  const id = APP_ID[style.id];
  if (!id || !style.melodic) continue;
  const slots = getSlotsPerBar(style);
  const tracks: string[] = [];
  for (const track of TRACKS) {
    const list = (style.melodic[track] as { variations?: (BassScaleData & { name: string })[] } | undefined)?.variations ?? [];
    if (list.length < 2) continue;
    const entries = list.map((v) => {
      const bars = v.loopBars ?? 1;
      const slot = degreeSlots(v);
      const steps = Array.from({ length: bars * slots }, (_, i) => slot(i));
      count++;
      return `      StyleVariation(${JSON.stringify(v.name)}, ${bars}, [${steps.join(', ')}]),`;
    });
    tracks.push(`    '${track}': [\n${entries.join('\n')}\n    ],`);
  }
  if (tracks.length) out.push(`  '${id}': {\n${tracks.join('\n')}\n  },`);
}

const dart = `// Generated by chord-composer's \`npm run variations:export\` (scripts/variations-export.ts)
// from the web's styles (src/lib/styles.ts). Do not edit: change them there and export again.
//
// Each variation is the steps the shared engine plays, one bar of the style's meter after
// another, as the web sends them.
part of 'style_presets.dart';

const styleVariations = <String, Map<String, List<StyleVariation>>>{
${out.join('\n')}
};
`;
const file = path.join(app, 'lib/core/data/style_variations.g.dart');
fs.writeFileSync(file, dart);
console.log(`variations:export: ${count} variations → ${file}`);
